apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: {{ .Values.proxy.hostname }}
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "athenaeum.labels" . | nindent 4 }}
spec: 
    secretName: {{ include "athenaeum.proxy.tls.secret_name" . }}
    issuerRef:
        name: letsencrypt-production
        kind: Issuer
    commonName: {{ .Values.proxy.hostname }}
    dnsNames:
    - {{ .Values.proxy.hostname }}
    acme:
        config:
        - http01:
            ingressClass: {{ .Values.proxy.ingress.class }}
          domains:
          - {{ .Values.proxy.hostname }}

