apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "athenaeum.proxy.service.name" .) }}
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.proxy.ingress.class }}
spec:
  tls:
    - secretName: {{ include "athenaeum.proxy.tls.secret_name" . }}
  rules:
    - host: {{ .Values.proxy.hostname }}
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ include "athenaeum.proxy.service.name" . }}
              servicePort: {{ .Values.proxy.ingress.port}}
