apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "%s-ingress" (include "athenaeum.proxy.service.name" .) }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - secretName: {{ include "athenaeum.proxy.tls.secret_name" . }}
  rules:
    - host: notebooks.staging.athenaeumnb.com
      http:
        paths:
          - path: "/"
            backend:
              serviceName: {{ include "athenaeum.proxy.service.name" . }}
              servicePort: {{ .Values.proxy.ingress.port}}
