apiVersion: v1
kind: Service
metadata:
  name: {{ include "athenaeum.proxy.service.name" . }}
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: {{ .Values.proxy.service.port }}
      targetPort: {{ .Values.proxy.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "athenaeum.service.selector" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "athenaeum.proxy.api.service.name" . }}
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.api.service.type }}
  ports:
    - port: {{ .Values.proxy.api.service.port }}
      targetPort: {{ .Values.proxy.api.service.targegPort }}
      protocol: TCP
  selector:
    {{- include "athenaeum.service.selector" . | nindent 4 }}
  