apiVersion: v1
kind: Service
metadata:
  name: proxy
  labels:
    app: {{ template "athenaeum.name" . }}
    chart: {{ template "athenaeum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "athenaeum.labels" . | nindent 4 }}
