apiVersion: v1
kind: Service
metadata:
  name: {{ include "athenaeum.proxy.service.name" . }}
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
spec:
  type: {{ .Values.proxy.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "athenaeum.service.selector" . | nindent 4 }}
