steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '$_GS_HELM_REPO_BUCKET_HEAD-$BRANCH_NAME/index.yaml', '.']
- name: 'devth/helm'
  args: [ 'helm', 'package', '--save=false', 'athenaeum']
- name: 'devth/helm'
  args: [ 'helm', 'repo', 'index', '--debug', '--merge', 'index.yaml', '.' ]
- name: 'gcr.io/cloud-builders/gsutil'
  args: [  'cp', 'index.yaml', '*.tgz', '$_GS_HELM_REPO_BUCKET_HEAD-$BRANCH_NAME' ]
substitutions:
  _BUILD_NAME: 'Athenaeum Helm Repo Update'

