steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '$_GS_HELM_REPO_BUCKET_HEAD-$BRANCH_NAME/index.yaml', '.']
  env: 
  - 'BUILD_NAME=${_BUILD_NAME}'
  - 'BRANCH_NAME=${BRANCH_NAME}'
  - 'REPO_NAME=${REPO_NAME}'
  - 'BUILD_DESCRIPTION=Pushed athenaeum helm chart package to heln repo $_GS_HELM_REPO_BUCKET_HEAD-$BRANCH_NAME'
- name: 'devth/helm'
  args: [ 'helm', 'package', '--save=false', 'athenaeum']
- name: 'devth/helm'
  args: [ 'helm', 'repo', 'index', '--debug', '--merge', 'index.yaml', '.' ]
- name: 'gcr.io/cloud-builders/gsutil'
  args: [  'cp', 'index.yaml', '*.tgz', '$_GS_HELM_REPO_BUCKET_HEAD-$BRANCH_NAME' ]
substitutions:
  _BUILD_NAME: 'Athenaeum Chart Helm Repo Update'
  _GS_HELM_REPO_BUCKET_HEAD: 'gs://momentlabs-helm'

