apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "athenaeum.fullname" . }}
  labels:
    app: {{ template "athenaeum.name" . }}
    component: hub
    chart: {{ template "athenaeum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "athenaeum.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "athenaeum.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: hub-db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.hub.db.pvc.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag }}"
          # image: gcr.io/momentlabs-jupyter/athenaeum-hub
          imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
          ports:
            - name: hub
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          volumeMounts:
          - mountPath: /srv/jupyterhub
            name: hub-db-volume
          # resources:
# {{ toYaml .Values.resources | indent 12 }}
#     {{- with .Values.nodeSelector }}
#       nodeSelector:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.tolerations }}
#       tolerations:
# {{ toYaml . | indent 8 }}
#     {{- end }}
