apiVersion: v1
kind: Service
metadata:
  name: {{ template "athenaeum.fullname" . }}
  labels:
    app: {{ template "athenaeum.name" . }}
    chart: {{ template "athenaeum.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.hub.service.type }}
  ports:
    - port: {{ .Values.hub.service.port }}
      targetPort: 8000
      protocol: TCP
      name: jupyterhub
  selector:
    app: {{ template "athenaeum.name" . }}
    release: {{ .Release.Name }}
