hub:
  debug: True
  image:
    repository: gcr.io/momentlabs-jupyter/athenaeum-hub
    tag: dev
    pullPolicy: Always
  auth:
    type: auth0
    auth0:
      subdomain: momentlabs
      client_id: "1bmk91W3XSgQ7XeD2U4ewbD5QYEBLJ1y"
      client_secret: "LhfMcwHklLkR8UPsf4kYOOsSmaef105AdEL1TJ62EejqvmWPd76Z-cSmYPNj036h"
      oauth_callback_url: "http://notebooks.staging.athenaeumnb.com/hub/oauth_callback"
      auth0_subdomain: "momentlabs"
      client_redirect_base_url: "https://notebooks.staging.athenaeumnb.com"  # This is used for adding redirects (e.g. logout) from auth0 to us.
  spawner:
    start_timeout: 300
    image_pull_policy: Always
    image_spec: jupyterhub/singleuser:0.9ß.2
    default_url: /lab

proxy:
  hostname: notebooks.staging.athenaeumnb.com
  secretToken: 1d16be9c9a48800df8f013841f747289e62054878cd948be0358560ecca2ea53