kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-configmap
  labels:
    app: athenaeum
data:
  config: |-
    hub:
      debug: {{ .Values.hub.debug }}
      uid: {{ .Values.hub.uid }}
      fs_gid: {{ .Values.hub.fs_gid }}
      image:
        repository: {{ .Values.hub.image.repository }}
        tag: {{ .Values.hub.image.tag }}
        pullPolicy: {{ .Values.hub.image.pullPolicy }}
      service:
        name: {{ include "athenaeum.hub.service.name" . }}
        type: {{ .Values.hub.service.type }}
      db:
        pvc:
          name: {{ .Values.hub.db.pvc.name }}
      auth:
        authenticator_class: {{ .Values.hub.auth.athenticator_class }}
      spawner:
        spawner_class: {{ .Values.hub.spawner.spawner_class }}
        start_timeout: {{ .Values.hub.spawner.start_timeout }}
        image_pull_policy: {{ .Values.hub.spawner.image_pull_policy }}
        image_spec: {{ .Values.hub.spawner.image_spec }}
        storage:
          user_storage_pvc_ensure: {{ .Values.hub.spawner.storage.user_storage_pvc_ensure }}
          user_storage_capacity: {{ .Values.hub.spawner.storage.user_storage_capacity }}
          storage_access_modes: {{ .Values.hub.spawner.storage.storage_access_modes }}
          pvc_name_template: {{ .Values.hub.spawner.storage.pvc_name_template }}
    proxy:
      hub_should_start: {{ .Values.proxy.hub_should_start }}
      service:
        name: {{ include "athenaeum.proxy.service.name" . }}
        type: {{ .Values.proxy.service.type }}


