kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-configmap
  labels:
    app: athenaeum
data:
  config: |-
    hub:
      debug: {{ .Values.hub.debug }}
      uid: {{ .Values.hub.uid }}
      fs_gid: {{ .Values.hub.fs_gid }}
      image: {{ toJson .Values.hub.image }}
      service:
        name: {{ include "athenaeum.hub.service.name" . }}
        type: {{ .Values.hub.service.type }}
      db: {{ toJson .Values.hub.db }}
      auth: {{ toJson .Values.hub.auth }}
      spawner: {{ toJson .Values.hub.spawner }}
    proxy:
      hub_should_start: {{ .Values.proxy.hub_should_start }}
      hostname: {{ .Values.proxyhostname }}
      image: {{ toJson .Values.proxy.image }}
      service:
        name: {{ include "athenaeum.proxy.service.name" . }}
        type: {{ .Values.proxy.service.type }}
      api:
        service:
            name: {{ include "athenaeum.proxy.api.service.name" . }}
            type: {{ .Values.proxy.api.service.type }}
            port: {{ .Values.proxy.api.service.port }}
            targetPort: {{ .Values.proxy.api.service.targetPort }}
      ingress: {{ .Values.proxy.ingress }}
