kind: ConfigMap
apiVersion: v1
metadata:
  name: hub-configmap
  labels:
    app: athenaeum
data:
  config: |-
    hub:
      debug: {{ .Values.hub.debug }}
      uid: {{ .Values.hub.uid }}
      fs_gid: {{ .Values.hub.fs_gid }}
      service:
        name: {{ .Values.hub.service.name }}
      spawner:
        spawner_class: {{ .Values.hub.spawner.spawner_class }}
        start_timeout: {{ .Values.hub.spawner.start_timeout }}
        storage:
          user_storage_pvc_ensure: {{ .Values.hub.spawner.storage.user_storage_pvc_ensure }}
          user_storage_capacity: {{ .Values.hub.spawner.storage.user_storage_capacity }}
          storage_access_modes: {{ .Values.hub.spawner.storage.storage_access_modes }}
          pvc_name_template: {{ .Values.hub.spawner.storage.pvc_name_template }}


