apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "athenaeum.hub.service.name" . }}
  labels:
    {{- include "athenaeum.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "athenaeum.labels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "athenaeum.labels" . | nindent 8 }}
    spec:
      serviceAccount: hub
      volumes:
        - name: hub-db-volume
          persistentVolumeClaim:
            claimName: {{ .Values.hub.db.pvc.name }}
        - name: hub-config
          configMap:
            name: hub-configmap
            items:
            - key: config
              path: config.yaml
      containers:
        - name: {{ include "athenaeum.hub.service.name" . }}
          image: "{{ .Values.hub.image.repository }}:{{ .Values.hub.image.tag }}"
          imagePullPolicy: {{ .Values.hub.image.pullPolicy }}
          env:
            - name: AUTH0_SUBDOMAIN 
              value: {{ .Values.hub.auth.auth0.subdomain }}
          ports:
            - name: hub
              containerPort: 8000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8000
          volumeMounts:
          - mountPath: /srv/jupyterhub
            name: hub-db-volume
          - mountPath: /etc/athenaeum/
            name: hub-config
          # resources:
# {{ toYaml .Values.resources | indent 12 }}
#     {{- with .Values.nodeSelector }}
#       nodeSelector:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.affinity }}
#       affinity:
# {{ toYaml . | indent 8 }}
#     {{- end }}
#     {{- with .Values.tolerations }}
#       tolerations:
# {{ toYaml . | indent 8 }}
#     {{- end }}
