apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebook-auth0-5f58a7790682b0ca077463b869
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: notebooks-production-auth0-5f58a7790682b0ca077463b869
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-auth0-5f58a7790682b0ca077463b869
spec:
  storageClassName: ""
  volumeName: notebook-auth0-5f58a7790682b0ca077463b869
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10G
---
