proxy:
  secretToken: "76b052a7ea4a97b46cbe8b5b312508a5b3b4f82cca7aac6a7f2edc2d78b7dd36"
  https:
    hosts: 
        - staging.atheneumnb.io
    letsencrypt:
        contactEmail: operations@momentlabs.io
  service:
    loadBalancerIP: 35.230.60.217

prePuller:
  hook:
    enabled: false

hub:
  image:
    name: momentlabs/jupyterhub-k8s
    tag: '00055'
  extraEnv:
      AUTH0_SUBDOMAIN: momentlabs
      # OAUTH_CLIENT_ID: "1bmk91W3XSgQ7XeD2U4ewbD5QYEBLJ1y"
      # OAUTH_CLIENT_SECRET: "LhfMcwHklLkR8UPsf4kYOOsSmaef105AdEL1TJ62EejqvmWPd76Z-cSmYPNj036h"
      # OAUTH_CALLBACK_URL: "http://staging.atheneumnb.io/hub/oauth_callback"

auth:
  # type: auth0
  # auth0:
  #   clientId: "1bmk91W3XSgQ7XeD2U4ewbD5QYEBLJ1y"
  #   clientSecret: "LhfMcwHklLkR8UPsf4kYOOsSmaef105AdEL1TJ62EejqvmWPd76Z-cSmYPNj036h"
  #   callbackUrl: "http://staging.atheneum.momentlabs.io/hub/oauth_callback"
    
  type: custom
  custom:
      className: oauthenticator.auth0.Auth0OAuthenticator
      config:
        client_id: "1bmk91W3XSgQ7XeD2U4ewbD5QYEBLJ1y"
        client_secret: "LhfMcwHklLkR8UPsf4kYOOsSmaef105AdEL1TJ62EejqvmWPd76Z-cSmYPNj036h"
        oauth_callback_url: "http://staging.atheneumnb.io/hub/oauth_callback"
        auth0_subdomain: "momentlabs"
        client_redirect_base_url: "https://staging.atheneumnb.io"  # This is used for adding redirects (e.g. logout) from auth0 to us.

  #  type: github
  # github:
  #   clientId: "d3daead7c1fe84b354ab"
  #   clientSecret: "3cc07c9525900bd1ddc454518f040ad6c3520576"
  #   callbackUrl: "http://jupyter.momentlabs.io/hub/oauth_callback"

# cull:
#   enabled: true
#   timeout: 86400 # 86400 = 1 day in seconds, 3600 = 1 hours in seconds.
#   every: 3600 

# prePuller:
#   continuous:
#     enabled: false
#   hook:
#       enabled: true

singleuser: 
  image: 
    name: jupyter/scipy-notebook
    tag: 96f2f777be6e
  memory:
    limit: 2G
    guarantee: .5G
  cpu:
    limit: 1.0
    guarantee: .5


