apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: jupyterhub
  labels:
    app: jupyterhub
    component: hub
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:  
      volumes:
      - name: hub-db
        persistentVolumeClaim:
          claimName: hub-db
      containers:
      - name: jupyterhub
        image: gcr.io/momentlabs-jupyter/athenaeum-hub
        ports: 
        - containerPort: 8000
        volumeMounts:
        - mountPath: /srv/jupyterhub
          name: hub-db

