apiVersion: v1
kind: Pod
metadata: 
  name: jupyter-notebook-test
  labels:
    app: athenaeum-test
    component: notebook
spec: 
  restartPolicy: Never
  volumes:
  - name: home
    persistentVolumeClaim:
      claimName: claim-jdr
  containers:
  - name:  notebook-test
    image: jupyterhub/singleuser:0.8
    # args: 
    # - jupyterhub-singleuser
    # - --debug  
    ports: 
    - containerPort: 8888
    volumeMounts:
    - mountPath: /home/jovyan
      name: home
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
        