apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: test-role
  namespace: default
rules:
- apiGroups: [""]     # core apis
  resources: ["pods", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
