{{- if .Values.cull.culler_app.enabled -}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: pod-culler
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "athenaeum.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "athenaeum.labels" . | nindent 8 }}
    spec:
      serviceAccountName: pod-culler
      containers:
        - name: culler
          image: {{ .Values.cull.image.repository }}:{{ .Values.cull.image.tag }}
          resources:
            requests:
              memory: 100Mi
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LABEL_SELECTOR
              value: {{ include "athenaeum.podCullerSelector" . | quote }}
            - name: MAX_AGE
              value: {{ .Values.cull.maxAge | quote }}
            - name: CULL_INTERVAL
              value: {{ .Values.cull.interval | quote }}
{{- end -}}
