{{- if .Values.cull.culler_app.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-culler
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-culler
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
rules:
- apiGroups:
    - ""      #  core apis
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: pod-culler
  labels:
    {{- include "athenaeum.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: pod-culler
roleRef:
  kind: Role
  name: pod-culler
  apiGroup: rbac.authorization.k8s.io
{{- end -}} 